name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Update apt
        run: sudo apt update
      - name: Install libs
        run: sudo apt install librust-pango-sys-dev librust-atk-sys-dev libsoup2.4-dev libgtk-3-dev libwebkit2gtk-4.0-dev # libgdk-pixbuf2.0-dev
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
